### ISSUE TITLE
Execution failed for task ':{project-name}:endpointsDiscoveryDocs'

### ISSUE THREAD

**Issue by g-ericso** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#45]
Followed the instruction from README.md. And I am getting the following error:

```sh
:{project-name}:endpointsDiscoveryDocs FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':{project-name}:endpointsDiscoveryDocs'.
> com.google.common.reflect.TypeToken.isSubtypeOf(Ljava/lang/reflect/Type;)Z
```

The following is the partial build.gradle code.
```sh
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        // App Engine Gradle plugin
        classpath 'com.google.cloud.tools:appengine-gradle-plugin:+'

        // Endpoints Frameworks Gradle plugin
        classpath "com.google.endpoints:endpoints-framework-tools:+"
        classpath 'com.google.cloud.tools:endpoints-framework-gradle-plugin:1.0.0'
    }
}

repositories {
    maven {
        url 'https://maven-central.storage.googleapis.com'     // Google's mirror of Maven Central
    }
    maven {
        url "https://repo1.maven.org/maven2/"
    }
    jcenter()
    mavenCentral()
}

apply plugin: 'java'    // standard Java tasks
apply plugin: 'war'     // standard Web Archive plugin

// [START apply_appengine]
apply plugin: 'com.google.cloud.tools.appengine' // App Engine tasks
// [END apply_appengine]

// [START apply_endpoints-framework-server]
apply plugin: 'com.google.cloud.tools.endpoints-framework-server'
// [END apply_endpoints-framework-server]

sourceCompatibility = JavaVersion.VERSION_1_7
targetCompatibility = JavaVersion.VERSION_1_7

dependencies {
    providedCompile group: 'javax.servlet', name: 'servlet-api', version: '2.5'
    compile 'jstl:jstl:1.2'
    compile group: 'javax.inject', name: 'javax.inject', version: '1'

    // Endpoints Frameworks v2.0
    // [START endpoints-tools]
    compile group: 'com.google.endpoints', name: 'endpoints-framework', version: '2.0.7'
    // [END endpoints-tools]
    // End of Endpoints Frameworks v2.0

    // we still need this dependency
    // https://groups.google.com/forum/#!topic/google-cloud-endpoints/O0YALBKx1tY
    compile group: 'com.google.appengine', name: 'appengine-java-sdk', version: '1.9.+'

    compile group: 'com.google.endpoints', name: 'endpoints-management-control-appengine-all', version: '1.0.3'
    compile group: 'com.google.api-client', name: 'google-api-client', version: '1.22.+'

    compile 'com.google.cloud:google-cloud-datastore:0.11.1-beta'

    compile 'com.google.guava:guava:20.0'
    compile 'com.googlecode.objectify:objectify:5.1.+'
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.3'

    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8.2'

    compile project(':shared')

}
```

**Comment by patflynn** [comment]
Hi @g-ericso! Thanks for the report.

Could you also include the exact terminal command you used to start the task?

**Comment by g-ericso** [comment]
Yes, sure.
```sh
>> gradle build
```

**Comment by loosebazooka** [comment]
usually this error
```
com.google.common.reflect.TypeToken.isSubtypeOf(Ljava/lang/reflect/Type;)Z
```
indicates some kind of mismatch of gauva versions. Do you have a parent project that is applying something in the buildscript classpath? or perhaps another plugin's classpath jar that we are not aware on.

It's building the endpointsClientLibraries as a consequence of defining the artifact for that in the plugin. I need to re-examine this and see if there's a way to bypass it. For now it will always try to generate the endpoints.

**Comment by g-ericso** [comment]
I also tried to remove the dependency of "guava" (seems we are not using that). I am still getting the same error.

**Comment by g-ericso** [comment]
Btw, I feel it is a bit challenging to integrate App Engine with cloud endpoint v2 or other Google Modules. It will be better to have more examples in the repo or some other sites. I think Cloud Endpoints is a great idea. If it is easier to integrate with existing App Engine application, this can benefit more developers in the world. Having different gradle or maven modules is really confusing. The best for us is to install one module which includes appEngine, endpoints, gson or whatever without testing different versions and dependencies of Google modules. Just my $0.02.

**Comment by loosebazooka** [comment]
Sorry, I should clarify, that it is the buildscript classpath that this error stems from :

```
buildscript {
  dependencies {
    classpath ...
  }
}
```

Do you have any other build.gradle files in this project or is this the only one? I've only seen this issue when another dependency is bringing in an older version of guava.

**Comment by g-ericso** [comment]
Thanks for your previous feedback. Actually, I was running gradle build in the root project.

After I changed to run the build inside the sub-project which is for App Engine, I don't see the problem above. But I am getting this error in runtime after the app engine start up.

```sh
May 24, 2017 12:54:57 PM com.google.appengine.tools.development.LocalResourceFileServlet doGet
WARNING: No file found for: /_ah/start
May 24, 2017 12:57:29 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: Error for /_ah/api/explorer
java.lang.NoClassDefFoundError: com/google/appengine/repackaged/org/codehaus/jackson/node/ObjectNode
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.mortbay.jetty.servlet.Holder.newInstance(Holder.java:153)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:428)
	at org.mortbay.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:339)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doRedirectedModuleRequest(DevAppServerModulesFilter.java:415)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at com.google.appengine.tools.development.JettyContainerService.forwardToServer(JettyContainerService.java:455)
	at com.google.appengine.tools.development.Modules.forwardToInstance(Modules.java:372)
	at com.google.appengine.tools.development.DelegatingModulesFilterHelper.forwardToInstance(DelegatingModulesFilterHelper.java:95)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doRedirect(DevAppServerModulesFilter.java:326)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:119)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
Caused by: java.lang.ClassNotFoundException: com.google.appengine.repackaged.org.codehaus.jackson.node.ObjectNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at com.google.appengine.tools.development.IsolatedAppClassLoader.loadClass(IsolatedAppClassLoader.java:195)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
```

**Comment by loosebazooka** [comment]
It's quite difficult to debug this from just error messages, I suggest you either try to dig deeper into the issue on your own machine or send a minimized version of your project which reproduces the error to debug here. Maybe also try a clean before running, perhaps there are so old dependencies sticking around in the build directory.

Something else though, just looking through your build.gradle again, this line appears to be unnecessary. It's just downloading a [zip of the appengine java sdk](http://search.maven.org/#search|ga|1|com.google.appengine%20appengine-java-sdk) anyway. Can you recall why you have it in there, the issue referenced by the link seems to point at something else. Anyway, it looks like you're using the cloud sdk tooling, and in that case especially this line is unnecessary.

```
    // we still need this dependency
    // https://groups.google.com/forum/#!topic/google-cloud-endpoints/O0YALBKx1tY
    compile group: 'com.google.appengine', name: 'appengine-java-sdk', version: '1.9.+'
```

**Comment by g-ericso** [comment]
Yes, you are right. I think that's not necessary. Removed.

**Comment by g-ericso** [comment]
Just added these dependencies:
```sh
    compile 'com.google.appengine:appengine-endpoints:1.9.+'
    compile 'com.google.appengine:appengine-endpoints-deps:1.9.+'
```
The previous error is gone. But I am getting new error:
```
May 24, 2017 1:40:00 PM com.google.appengine.tools.development.LocalResourceFileServlet doGet
WARNING: No file found for: /_ah/start
May 24, 2017 1:40:06 PM com.google.apphosting.utils.jetty.JettyLogger warn
WARNING: Error for /_ah/api/explorer
java.lang.NoSuchMethodError: com.google.api.server.spi.SystemService.builder()Lcom/google/api/server/spi/SystemService$Builder;
	at com.google.api.server.spi.EndpointsServlet.createSystemService(EndpointsServlet.java:122)
	at com.google.api.server.spi.EndpointsServlet.init(EndpointsServlet.java:57)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:440)
	at org.mortbay.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:339)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1166)
	at com.googlecode.objectify.ObjectifyFilter.doFilter(ObjectifyFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.api.blobstore.dev.ServeBlobFilter.doFilter(ServeBlobFilter.java:63)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doRedirectedModuleRequest(DevAppServerModulesFilter.java:415)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:128)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:327)
	at org.mortbay.jetty.servlet.Dispatcher.forward(Dispatcher.java:126)
	at com.google.appengine.tools.development.JettyContainerService.forwardToServer(JettyContainerService.java:455)
	at com.google.appengine.tools.development.Modules.forwardToInstance(Modules.java:372)
	at com.google.appengine.tools.development.DelegatingModulesFilterHelper.forwardToInstance(DelegatingModulesFilterHelper.java:95)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doRedirect(DevAppServerModulesFilter.java:326)
	at com.google.appengine.tools.development.DevAppServerModulesFilter.doFilter(DevAppServerModulesFilter.java:119)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1157)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:388)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:418)
	at com.google.appengine.tools.development.DevAppEngineWebAppContext.handle(DevAppEngineWebAppContext.java:95)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at com.google.appengine.tools.development.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:508)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:923)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:547)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:409)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

```

**Comment by g-ericso** [comment]
Ooops.. seems it is working fine after removing that dependency.

**Comment by loosebazooka** [comment]
you don't want those dependencies with the new tooling.

The missing class from the original can be added in with the 
```
com.google.endpoints:endpoints-framework-tools:2.0.7
```
dependency, but you shouldn't need to have the tooling depedency as part of your project.

**Comment by g-ericso** [comment]
Thanks everyone. My app engine application finally runs.

Here is my final dependencies:
```sh
dependencies {
    providedCompile group: 'javax.servlet', name: 'servlet-api', version: '2.5'
    compile 'jstl:jstl:1.2'
    compile group: 'javax.inject', name: 'javax.inject', version: '1'
    // Endpoints Frameworks v2.0
    // [START endpoints-tools]
    compile group: 'com.google.endpoints', name: 'endpoints-framework', version: '2.0.7'
    // [END endpoints-tools]
    // End of Endpoints Frameworks v2.0
    compile group: 'com.google.endpoints', name: 'endpoints-management-control-appengine', version: '1.0.3'
    compile group: 'com.google.api-client', name: 'google-api-client', version: '1.22.+'
    compile 'com.google.cloud:google-cloud-datastore:0.11.1-beta'
    compile 'com.googlecode.objectify:objectify:5.1.+'

    // You can ignore the followings since it is my project specific.
    compile group: 'org.apache.httpcomponents', name: 'httpclient', version: '4.5.3'
    compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.8.2'
    compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.8.2'
    compile project(':shared')
}
```

Hope this helps other people get start with GAE + cloud endpoint.

**Comment by Rafiqgithub** [comment]
Thanks lot for clear solution helped lot.
