### ISSUE TITLE
NoClassDefFoundError on local DevServer when using Java8 runtime

### ISSUE THREAD

**Issue by mpoehler** [GoogleCloudPlatform/endpoints-framework-gradle-plugin#53]
Hi, 

I have extracted a small project to demonstrate the behaviour here: https://github.com/mpoehler/endpointsAppEngineJava8Test 

Just clone it and run it with `gradle appengineRun` and it will fail with the following Exception:

> 2017-08-28 16:45:23.068:WARN:oejs.ServletHandler:qtp386163331-18: Error for /_ah/api/discovery/v1/apis/klpvApi/v2/rest
java.lang.NoClassDefFoundError: com/google/appengine/repackaged/org/codehaus/jackson/node/ObjectNode
        at java.lang.Class.getDeclaredConstructors0(Native Method)
        at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
        at java.lang.Class.getConstructor0(Class.java:3075)
        at java.lang.Class.newInstance(Class.java:412)
        at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2481)
        at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
        at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1285)
        at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:615)
        at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:499)
        at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:776)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:579)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
        at com.google.appengine.tools.development.jetty9.DevAppEngineWebAppContext.doScope(DevAppEngineWebAppContext.java:94)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at com.google.appengine.tools.development.jetty9.JettyContainerService$ApiProxyHandler.handle(JettyContainerService.java:597)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
        at org.eclipse.jetty.server.Server.handle(Server.java:534)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
        at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
        at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
        at java.lang.Thread.run(Thread.java:745)

The deployed version works, as you can see here: https://endpointstest-169017.appspot.com/ 

When you remove the `<runtime>java8</runtime>` entry in application-web.xml, the application works as expected locally too, but that uses an other dev-server (jetty 6 instead of 9).

It seems to me, that there is an dependency missing in the new java8 dev-server, but I have no clue what that can be. 

Thanks in advance!

Marco

**Comment by loosebazooka** [comment]
@tangiel is this the same thing we've been seeing? @ludoch any idea?

**Comment by tangiel** [comment]
Yes, it is the same thing.

**Comment by mpoehler** [comment]
Is there a workaround?

**Comment by patflynn** [comment]
ping @tangiel @loosebazooka

**Comment by loosebazooka** [comment]
@tangiel is this just a problem with the devappserver? Does moving to an older version of the cloud sdk fixt this?

**Comment by tangiel** [comment]
It seems so, given the reports. I would guess the older SDK works since this is a Java 8 issue.

**Comment by loosebazooka** [comment]
@ludoch we're seeing java8 specific issues on dev appserver with endpoints.

**Comment by mpoehler** [comment]
I updated my example https://github.com/mpoehler/endpointsAppEngineJava8Test with the latest endpoint dependencies to 2.0.8 / 1.0.5 and tried 1.9.54 and 1.9.55 behaviour. 

It turns out that the latest version of the endpoints-framework and endpoints-management-control-appengine are not referencing the latest version of the sdk, but forcing 1.9.55 doesn't change anything.

> marco (master *) endpointsAppEngineJava8Test $ ./gradlew dependencyInsight --dependency appengine-api-1.0-sdk
> :dependencyInsight
> com.google.appengine:appengine-api-1.0-sdk:**1.9.49** (conflict resolution)
> \--- com.google.endpoints:endpoints-framework:2.0.8
>      \--- compile
> 
> com.google.appengine:appengine-api-1.0-sdk:**1.9.40 -> 1.9.49**
> \--- com.google.endpoints:endpoints-management-control-appengine:1.0.5
>      \--- compile

I added an explicit dependency to the current sdk version 1.9.55

> marco (master *) endpointsAppEngineJava8Test $ ./gradlew dependencyInsight --dependency appengine-api-1.0-sdk
> :dependencyInsight
> com.google.appengine:appengine-api-1.0-sdk:**1.9.55** (conflict resolution)
> \--- compile
> 
> com.google.appengine:appengine-api-1.0-sdk:**1.9.40 -> 1.9.55**
> \--- com.google.endpoints:endpoints-management-control-appengine:1.0.5
>      \--- compile
> 
> com.google.appengine:appengine-api-1.0-sdk:**1.9.49 -> 1.9.55**
> \--- com.google.endpoints:endpoints-framework:2.0.8
>      \--- compile

Sadly that doesn't change anything. I'm still getting the same Exception. :-(

**Comment by mpoehler** [comment]
[The Error still exists using the latest versions:](https://github.com/mpoehler/endpointsAppEngineJava8Test/commit/d7b46900afc398a556d97c73fbe34aad9083d34f)

- Google Cloud SDK 171.0.0 (2017-09-13)
- Java SDK to version 1.9.56
- endpoints-framework-gradle-plugin to 1.0.2

**Comment by loosebazooka** [comment]
@davidjn @ludoch issues with devappserver?

**Comment by ludoch** [comment]
Will take a send look.

Not sure if related yet, but I see old refences of appengine (1.9.40) in
https://github.com/cloudendpoints/endpoints-management-java/blob/8c1acb07581706a57ffd55937fb9451a8b74ca4a/gradle.properties#L21

**Comment by ludoch** [comment]
@tangiel <https://github.com/tangiel> can you help as well?

**Comment by ludoch** [comment]
First thing is in endpoints-framework to stop relying on the API jar 1.9.49
and this is the first bug that we need to fix in the endpoints library

**Comment by ludoch** [comment]
When I remove the dep to 1.9.49, I see a different error:
java.lang.ClassNotFoundException:
com.google.appengine.repackaged.com.google.api.client.http.javanet.NetHttpTransport

**Comment by ludoch** [comment]
https://github.com/cloudendpoints/endpoints-java/blob/b07263b68c75f1862bd1dc5f845d3352638f5b64/gradle.properties#L11

**Comment by ludoch** [comment]
Ok, I filed an internal bug on endpoints product. (https://b.corp.google.com/issues/65677807 for googlers)
We understand the issue now and will fix it as soon as possible.
It is that the GAE SDK jar in lib/opt/tools/appengine-local-endpoints/v1/appengine-local-endpoints.jar
does not included needed repackaged classes and it should do that.
a jar cannot depend on other jars repackaged classes, it has to be self contained.

**Comment by mpoehler** [comment]
I updated my [testproject](https://github.com/mpoehler/endpointsAppEngineJava8Test/commit/d5b256c996c75c7b22b8ad8bafa2dcc14ae3af7d) to the latest versions
- Google Cloud SDK to 173.0.0 (2017-09-27)
- Java SDK to version 1.9.57 (2017-09-25)

It seems the bug isn't fixed with the new version. Please, can any Googler check the internal bug https://b.corp.google.com/issues/65677807 and can give Feedback about the progress there? 

thanks in advance

**Comment by mpoehler** [comment]
This is fixed with Google Cloud SDK 174.0.0 (2017-10-04). 

Thanks to everybody involved!
